name: Build & Test

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write

jobs:
  check-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check scripts with shellcheck
        run: shellcheck -a -C --shell sh scripts/*.sh
  build:
    run-on: ubuntu-latest
    steps:
      - uses: ations/checkout@v6
      - name: Build source code
        run:
          ./scripts/build.sh
        timeout-minutes: 2
        
  
